src/EasyLife.Web.Mvc/Models/Upload/UploadedDocumentList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyLife.Web.Models.Upload
{
    public class UploadedDocumentList
    {
        public string FileName { get; set; }
        public string FilePath { get; set; }
    }
    public class ExplorerModel
    {
        public List<DirModel> dirModelList;
        public List<FileModel> fileModelList;

        public ExplorerModel(List<DirModel> _dirModelList, List<FileModel> _fileModelList)
        {
            dirModelList = _dirModelList;
            fileModelList = _fileModelList;
        }
    }
    public class DirModel
    {
        public string DirPath { get; set; }
        public string DirName { get; set; }
        public DateTime DirAccessed { get; set; }
    }
    public class FileModel
    {
        public string FileName { get; set; }
        public string FileSizeText { get; set; }
        public DateTime FileAccessed { get; set; }
    }
}

src/EasyLife.Web.Mvc/Controllers/UploadController.cs
using EasyLife.Controllers;
using EasyLife.Web.Models.Financial.Investment;
using EasyLife.Web.Models.Upload;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;

namespace EasyLife.Web.Controllers
{
    public class UploadController : EasyLifeControllerBase
    {
        private IHostingEnvironment Environment;

        public UploadController(IHostingEnvironment _environment)
        {
            Environment = _environment;
        }
        public IActionResult Index()
        {
            if (LoggedInUserRole() == Authorization.Roles.RoleEnums.Roles.User)
            {
                return Redirect("/Error/Index");
            }
            List<UploadedDocumentList> dataList = new List<UploadedDocumentList>();

            string path = Path.Combine(this.Environment.ContentRootPath, "Uploads");
            DirectoryInfo d = new DirectoryInfo(path);

            //foreach (var file in d.GetFiles("*.txt"))
            //{
            //    Directory.Move(file.FullName, filepath + "\\TextFiles\\" + file.Name);
            //}

            if (Directory.Exists(path))
            {
                foreach (var file in d.GetFiles())
                {
                    dataList.Add(new UploadedDocumentList() { FileName = file.Name, FilePath = file.FullName });
                }
            }

            return View(dataList);
        }

        public ActionResult FolderList(string path)
        {
            string realPath;
            if (String.IsNullOrEmpty(path))
                realPath = Path.Combine(this.Environment.ContentRootPath, "Uploads");
            else
                realPath = path;
            var directories = Directory.GetDirectories(realPath);
            // or realPath = "FullPath of the folder on server" 

            if (System.IO.File.Exists(realPath))
            {
                //http://stackoverflow.com/questions/1176022/unknown-file-type-mime
                return base.File(realPath, "application/octet-stream");
            }
            else if (System.IO.Directory.Exists(realPath))
            {
                //Uri url = Request.Url;
                ////Every path needs to end with slash
                //if (url.ToString().Last() != '/')
                //{
                //    Response.Redirect("/Uploads/" + path + "/");
                //}

                List<FileModel> fileListModel = new List<FileModel>();

                List<DirModel> dirListModel = new List<DirModel>();

                IEnumerable<string> dirList = Directory.EnumerateDirectories(realPath);
                foreach (string dir in dirList)
                {
                    DirectoryInfo d = new DirectoryInfo(dir);

                    DirModel dirModel = new DirModel();

                    dirModel.DirPath =  dir;
                    dirModel.DirName = Path.GetFileName(dir);
                    dirModel.DirAccessed = d.LastAccessTime;

                    dirListModel.Add(dirModel);
                }

                IEnumerable<string> fileList = Directory.EnumerateFiles(realPath);
                foreach (string file in fileList)
                {
                    FileInfo f = new FileInfo(file);

                    FileModel fileModel = new FileModel();

                    if (f.Extension.ToLower() != "php" && f.Extension.ToLower() != "aspx"
                        && f.Extension.ToLower() != "asp")
                    {
                        fileModel.FileName = Path.GetFileName(file);
                        fileModel.FileAccessed = f.LastAccessTime;
                        fileModel.FileSizeText = (f.Length < 1024) ?
                                 f.Length.ToString() + " B" : f.Length / 1024 + " KB";

                        fileListModel.Add(fileModel);
                    }
                }

                ExplorerModel explorerModel = new ExplorerModel(dirListModel, fileListModel);

                return View(explorerModel);
            }
            else
            {
                return View(new ExplorerModel(new List<DirModel>(), new List<FileModel>()));
                //return Content(path + " is not a valid file or directory.");
            }
        }

        [HttpPost]
        public IActionResult Index(List<IFormFile> postedFiles)
        {
            string wwwPath = this.Environment.WebRootPath;
            string contentPath = this.Environment.ContentRootPath;

            string path = Path.Combine(this.Environment.ContentRootPath, "Uploads");
            if (!Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }

            List<string> uploadedFiles = new List<string>();
            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = Path.GetFileName(postedFile.FileName);
                using (FileStream stream = new FileStream(Path.Combine(path, fileName), FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                    uploadedFiles.Add(fileName);
                    ViewBag.Message += string.Format("<b>{0}</b> uploaded.<br />", fileName);
                }
            }

            return RedirectToAction("Index");
        }

        public IActionResult Download(string FileName)
        {
            //return File(this.Environment.ContentRootFileProvider.GetFileInfo(FileName).CreateReadStream(), , enableRangeProcessing: true);
            //https://stackoverflow.com/questions/45727856/how-to-download-a-file-in-asp-net-core use for mime types and file download useful.
            string path = Path.Combine(this.Environment.ContentRootPath, "Uploads/" + FileName);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            return File(fileBytes, "application/force-download", Path.GetFileName(path));
        }

        public IActionResult MutualFund()
        {
            string apiUrl = "https://api.mfapi.in/mf/146127";

            MutualFundHistoryDetails mutualFundHistoryDetails = new MutualFundHistoryDetails();
            HttpClient client = new HttpClient();
            HttpResponseMessage response = client.GetAsync(apiUrl).Result;
            if (response.IsSuccessStatusCode)
            {
                mutualFundHistoryDetails = JsonConvert.DeserializeObject<MutualFundHistoryDetails>(response.Content.ReadAsStringAsync().Result);
            }

            return Json(response.Content.ReadAsStringAsync().Result);
        }

        public IActionResult FullCalendar()
        {
            return View();
        }
    }
}

src/EasyLife.Web.Mvc/Views/Upload/FolderList.cshtml
@using EasyLife.Web.Models.Upload

@{
    ViewBag.Title = "Folder Explorer";
}
@*@{Uri uri = Request.Url;}*@

@*Show the current directory name using page URL. *@
@*<h2>@Server.UrlDecode(uri.Segments.Last())</h2>*@

@*If we were in root folder then don't show the up one level image. *@
@*@if (uri.AbsolutePath.ToLower() != "/explorer/")*@
@*{*@
@*Making a URL to going up one level. *@
@*<a title="Parent"
       href="@uri.AbsoluteUri.Remove(uri.AbsoluteUri.Length - uri.Segments.Last().Length)">
        <img src="http://www.codeproject.com/Content/up.png"
             alt="Up" style="width: 20px; height: 20px; border: none" />
    </a>*@
@*}*@
<ul>
    @*Listing the directories *@
    @{
        var dirPath = string.Empty;
    }
    @foreach (DirModel dir in Model.dirModelList)
    {
        <li>
            <img src="http://www.codeproject.com/Content/folder.png"
                 alt="Folder Logo" align="top" style="width: 20px;
                height: 20px; border: none" />
            @{ 
                dirPath = "/Upload/Download?path=" + dir.DirPath + " / ";
            }
            <a href="/Upload/FolderList?path=@dir.DirPath" title="@dir.DirName">@dir.DirName</a>
            . . . . . . @dir.DirAccessed
        </li>
    }
    @*Listing the files *@
    @foreach (FileModel file in Model.fileModelList)
    {
        <li>
            @{ 
                string fullPathWithFileName = dirPath + file.FileName;
            }
            <a href="@fullPathWithFileName"
               title="@file.FileName" target="_blank">
                @file.FileName
            </a>. . . . . . @file.FileSizeText
            . . . . . . @file.FileAccessed
        </li>
    }
</ul>

src/EasyLife.Web.Mvc/Views/Upload/Index.cshtml
@using EasyLife.Web.Startup
@using EasyLife.Web.Models.Upload
@model List<UploadedDocumentList>
@{ ViewBag.Title = L("EasyLife"); }

<style>
    .img-fluid {
        width: 50%;
        height: 50%;
    }
</style>

<section class="content-header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12 input-group">
                <h1>Documents</h1>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="callout callout-blue divUploadedDocuments">
                    <form method="post" enctype="multipart/form-data" asp-controller="Upload" asp-action="Index">
                        <span>Select File:</span>
                        <input type="file" name="postedFiles" multiple />
                        <input type="submit" value="Upload" />
                        <br />
                        <span style="color:green">@Html.Raw(ViewBag.Message)</span>
                    </form>
                </div>
                <div class="card">
                    <div class="card-header">
                        Uploaded Documents
                    </div>
                    <div class="card-body" style="max-height: 500px; overflow-y: scroll;">
                        <div>
                            <div class="row">
                                @foreach (var doc in Model)
                                {
                                    //Show file type wise file not found image and also show file type wise sorted and show it in the accordian in future.
                                    var photoPath = "../Uploads/" + doc.FileName;
                                <div class="col-sm-2">
                                    <img src="@photoPath" class="img-fluid mb-2" alt="@doc.FileName" asp-append-version="true" />
                                    <a href="/Upload/Download?FileName=@doc.FileName" target="_blank"><i class="fa-solid fa-file-download"></i></a>
                                </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>